// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.bo.salesdemo.ebay.finding.api;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

/**
 * 
 * Defines the type of treatment to be applied to a discounted item,
 * either Strike-Through Pricing (STP) or Minimum Advertised Price (MAP). 
 * 
 */
public enum PriceTreatmentEnum {

    /**
     * 
   * STP stands for Strike-Through Pricing.
   * 
     */
    STP("STP"),
  

    /**
     * 
   * MAP stands for Miminum Advertised Price.
   * 
     */
    MAP("MAP");
  
  
    private final String value;
  
    PriceTreatmentEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    @NonNull
    public static PriceTreatmentEnum fromValue(@Nullable String v) {
        if (v != null) {
            for (PriceTreatmentEnum c: PriceTreatmentEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}